// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WinFormsApp1;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp1.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Days")
                        .HasColumnType("integer");

                    b.Property<int?>("Mess_ID")
                        .HasColumnType("integer");

                    b.Property<string>("TimeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("d_type")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("patentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Mess_ID");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("WinFormsApp1.RuleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleDetails");
                });

            modelBuilder.Entity("WinFormsApp1.RuleMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RuleMessages");
                });

            modelBuilder.Entity("WinFormsApp1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasFingerprints")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasInn")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPatent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPolicy")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighQualify")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLongStay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<bool>("KnowRussian")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PatentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProgramResetelment")
                        .HasColumnType("boolean");

                    b.Property<string>("VisitPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WinFormsApp1.Rule", b =>
                {
                    b.HasOne("WinFormsApp1.RuleMessage", "RuleMessage")
                        .WithMany("Rules")
                        .HasForeignKey("Mess_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RuleMessage");
                });

            modelBuilder.Entity("WinFormsApp1.RuleDetail", b =>
                {
                    b.HasOne("WinFormsApp1.Rule", "Rule")
                        .WithMany("RuleDetails")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("WinFormsApp1.Rule", b =>
                {
                    b.Navigation("RuleDetails");
                });

            modelBuilder.Entity("WinFormsApp1.RuleMessage", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
